# Generated by Django 5.1.1 on 2024-09-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('symbol', models.CharField(default='', max_length=2)),
                ('description', models.TextField(default='')),
                ('cover_image', models.ImageField(blank=True, default='', null=True, upload_to='periodic_table/elements_cover/')),
                ('bohr_model', models.ImageField(blank=True, default='', null=True, upload_to='periodic_table/elements_bohr_model/')),
                ('atomic_number', models.IntegerField(default=0)),
                ('atomic_mass', models.FloatField(default=0)),
                ('electrons_number', models.IntegerField(default=0)),
                ('neutrons_number', models.IntegerField(default=0)),
                ('density', models.FloatField(blank=True, default=0)),
                ('melting_point', models.FloatField(blank=True, default=0)),
                ('boiling_point', models.FloatField(blank=True, default=0)),
                ('state_matter', models.CharField(default='', max_length=20)),
                ('electronic_configuration', models.TextField(default='')),
                ('electron_distribution', models.CharField(default='', max_length=50)),
                ('ionic_states', models.CharField(blank=True, max_length=100)),
                ('history_and_discovery', models.TextField(blank=True, default='')),
                ('chemical_properties', models.TextField(blank=True, default='')),
                ('usage', models.TextField(blank=True, default='')),
                ('extra_information', models.TextField(blank=True, default='')),
            ],
        ),
    ]
