# Generated by Django 5.0.6 on 2024-07-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/default.png', upload_to='users/avatars/'),
        ),
    ]
