# Generated by Django 5.0.6 on 2024-07-24 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='learn_lab/files/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='learn_lab.activitylevel'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='learn_lab.activitysubject'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='learn_lab/files/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
