# Generated by Django 5.0.6 on 2024-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='learn_lab/files/'),
        ),
    ]
