# Generated by Django 5.0.6 on 2024-07-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_lab', '0002_alter_activity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='learn-lab/files/thumbnails/'),
        ),
    ]
