# Generated by Django 5.1.1 on 2024-09-26 15:13

import learn_lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_lab', '0002_alter_activity_content_alter_activity_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=learn_lab.models.file_upload),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
