# Generated by Django 5.0.6 on 2024-07-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('simbol', models.CharField(max_length=5)),
                ('element_cover', models.ImageField(blank=True, default='', upload_to='table_elements/elements_cover/')),
                ('bohr_model', models.ImageField(blank=True, default='', upload_to='table_elements/elements_bohr_model/')),
                ('atomic_number', models.IntegerField(default=0)),
                ('atomic_mass', models.FloatField(default=0)),
                ('electrons_number', models.IntegerField(default=0)),
                ('neutrons_number', models.IntegerField(default=0)),
                ('density', models.FloatField(default=0)),
                ('melting_point', models.FloatField(default=0)),
                ('boiling_point', models.FloatField(default=0)),
                ('state_matter', models.CharField(default='', max_length=20)),
                ('electronic_configuration', models.TextField(default='')),
                ('ionic_states', models.CharField(blank=True, max_length=100)),
                ('discoverer', models.CharField(blank=True, max_length=100)),
                ('year_discovered', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
