# Generated by Django 5.0.6 on 2024-07-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_elements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='simbol',
            new_name='symbol',
        ),
    ]
