# Generated by Django 5.0.6 on 2024-06-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('simbol', models.CharField(max_length=5)),
                ('element_cover', models.ImageField(blank=True, default='', upload_to='tabaela_elementos/elements_cover/')),
                ('atomic_number', models.IntegerField()),
                ('atomic_mass', models.IntegerField()),
            ],
        ),
    ]
