# Generated by Django 5.0.6 on 2024-06-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_elementos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='atomic_mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='elements',
            name='element_cover',
            field=models.ImageField(blank=True, default='', upload_to='tabela_elementos/elements_cover/'),
        ),
    ]
